# 1. Image Node LTS
FROM node:18-alpine

# 2. Répertoire dans le container
WORKDIR /app

# 3. Copier package.json
COPY package*.json ./

# 4. Installer les dépendances
RUN npm install --production

# 5. Copier tout le projet
COPY . .

# 6. Exposer le port utilisé par ton server.js (Render utilise un PORT dynamique)
EXPOSE 10000

# 7. Commande pour démarrer
CMD ["node", "server.js"]
